// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:195219570314:web:5d6a2f5f94bd82cb57f773',
    messagingSenderId: '195219570314',
    projectId: 'notify-52476',
    authDomain: 'notify-52476.firebaseapp.com',
    storageBucket: 'notify-52476.firebasestorage.app',
    measurementId: 'G-24W0SD3YCN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:195219570314:android:4f7e38941cfb0ea957f773',
    messagingSenderId: '195219570314',
    projectId: 'notify-52476',
    storageBucket: 'notify-52476.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:195219570314:ios:5ce632fcb7e2515457f773',
    messagingSenderId: '195219570314',
    projectId: 'notify-52476',
    storageBucket: 'notify-52476.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:195219570314:ios:5ce632fcb7e2515457f773',
    messagingSenderId: '195219570314',
    projectId: 'notify-52476',
    storageBucket: 'notify-52476.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '',
    appId: '1:195219570314:web:e2b796df621eb4e357f773',
    messagingSenderId: '195219570314',
    projectId: 'notify-52476',
    authDomain: 'notify-52476.firebaseapp.com',
    storageBucket: 'notify-52476.firebasestorage.app',
    measurementId: 'G-GSMVVVCHMY',
  );
}
